"""initial-migration

Revision ID: 77409ff0e6ff
Revises: 
Create Date: 2021-07-02 20:49:44.929429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77409ff0e6ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workOrders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serviceId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('orderDate', sa.DateTime(), nullable=False),
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('employeeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customerId'], ['services.id'], ),
    sa.ForeignKeyConstraint(['employeeId'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workOrders')
    op.drop_table('services')
    op.drop_table('employees')
    # ### end Alembic commands ###
